name: Deploy Cloud Functions

on:
  push:
    branches: [main]
    paths: ['functions/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Build functions
        run: |
          cd functions
          npm ci
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BORICHATV5 }}'
          projectId: 'borichatv5'
          channelId: live
          targets: functions

